default:
  image: ubuntu:latest
  tags:
    - docker

.commons: &commons
  only:
    - merge_requests

begin-test:
  <<: *commons
  stage: build
  script:
    - echo "Checking MR for $GITLAB_USER_LOGIN..."

check-backend:
  <<: *commons
  stage: test
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
  script:
    - echo "Checking backend..."
    - echo "Checking linting..."
    - python -m black --check .
    - echo "Checking tests..."
    - python manage.py test

check-frontend:
  <<: *commons
  stage: test
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  script:
    - echo "Checking frontend..."
    - echo "Checking linting..."
    - npm run lint
    - echo "Checking tests..."
    - npm test
